
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 1000ms
    database: 0
    keys:
      archive-key: archive-key
      latest-post: latest-post

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /blog
    username: crux
    password: 123456
    publisher-confirms: true

  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

server:
  port: 8080
logging:
  level:
    root: info
    com.miueon.blog.mapper: trace
    com.miueon.blog.filter: trace

  pattern:
    console: '%p%m%n'

mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


