
spring:
  application:
    name: Blog
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 1000ms
    database: 0
  aop:
    proxy-target-class: true
  mvc:
    log-request-details: true
server:
  port: 8080
logging:
  level:
    root: warn
    com.miueon.blog.mapper: trace
    com.miueon.blog.filter: trace

  pattern:
    console: '%p%m%n'

mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml